### ISSUE TITLE
mbed-cli offers no progress indicator for 'update'

### ISSUE THREAD

**Issue by rgrover** [ARMmbed/mbed-cli#136]
Users would benefit from a progress indicator when calling `mbed-cli update`.

**Comment by MarceloSalazar** [comment]
Here is good evidence on why we need a bar with progress indicator: https://github.com/ARMmbed/mbed-cli/issues/367

Our colleague Xiao based in Shanghai is seeing mbed CLI being stuck (network there is really slow)

**Comment by BruceBuckland** [comment]
I don't know if it is relevant, but I was having the same problem - seemingly forever mbed add's.  So much so that I killed and restarted them several times.  Then i used the -vv as per the above suggestion and progress was much much faster (before I got 1 MB downloaded of the mbed-dev repo in about 45 minutes, after it took about 3 minutes to get to 3.2MB.  It is big so it will take a while, but it is moving.

**Comment by tweety9999** [comment]
I will commit

**Comment by screamerbg** [comment]
@tweety9999 @BruceBuckland @SeppoTakalo PR #593 introduces this. Please try it out and let me know.

**Comment by screamerbg** [comment]
Now implemented and available in the official versions of Mbed CLI
