### ISSUE TITLE
mbed-cli is misinterpreting return codes from child tools

### ISSUE THREAD

**Issue by bremoran** [ARMmbed/mbed-cli#266]
For example: 

```
mbedgt: exited with code -10
[mbed] ERROR: "mbedgt" returned error code 246.
```

Here, mbed-cli has reported `(unsigned)rc & 0xFF`.

**Comment by screamerbg** [comment]
Bump
@bremoran @PrzemekWirkus @bridadan

**Comment by bridadan** [comment]
I have no problems with changing greentea to return positive codes. But if we're changing return codes we should probably go ahead and document them at the same time :smile: 

@mazimkhan Any chance we could get this work scheduled?

**Comment by screamerbg** [comment]
@bridadan @mazimkhan Any update on this?

**Comment by mfiore02** [comment]
Bump

This is causing our internal Jenkins environment to return false positives. One or more tests fail but python (mbed test) returns 0 which causes the job to report success instead of failure.
Seems to possibly be platform or test dependent. I have one platform where a RTOS test is failing and python correctly returns non-zero which causes the job to fail.

`
mbedgt: test case results: 156 OK / 1 ERROR
mbedgt: completed in 930.63 sec
mbedgt: exited with code 1
[mbed] Working path "C:\Users\Jenkins\workspace\mbed\platform-xdot-unit-tests\test" (library)
[mbed] Exec "python -u C:\Users\Jenkins\workspace\mbed\platform-xdot-unit-tests\test\mbed-os\tools\test.py -t GCC_ARM -m XDOT_L151CC -c --source C:\Users\Jenkins\workspace\mbed\platform-xdot-unit-tests\test --build C:\Users\Jenkins\workspace\mbed\platform-xdot-unit-tests\test\BUILD\tests\XDOT_L151CC\GCC_ARM --test-spec C:\Users\Jenkins\workspace\mbed\platform-xdot-unit-tests\test\BUILD\tests\XDOT_L151CC\GCC_ARM\test_spec.json -v" in C:\Users\Jenkins\workspace\mbed\platform-xdot-unit-tests\test
[mbed] Exec "mbedgt --test-spec C:\Users\Jenkins\workspace\mbed\platform-xdot-unit-tests\test\BUILD\tests\XDOT_L151CC\GCC_ARM\test_spec.json -V" in C:\Users\Jenkins\workspace\mbed\platform-xdot-unit-tests\test
[mbed] ERROR: "mbedgt" returned error code 1.
[mbed] ERROR: Command "mbedgt --test-spec C:\Users\Jenkins\workspace\mbed\platform-xdot-unit-tests\test\BUILD\tests\XDOT_L151CC\GCC_ARM\test_spec.json -V" in "C:\Users\Jenkins\workspace\mbed\platform-xdot-unit-tests\test"
---

C:\Users\Jenkins\workspace\mbed\platform-xdot-unit-tests\test>exit 1 
Build step 'Execute Windows batch command' marked build as failure
Finished: FAILURE
`

Another platform has a RTC test that is failing, but python returns 0 and the job appears to succeed.

`
mbedgt: test case results: 162 OK / 1 ERROR
mbedgt: completed in 745.27 sec
[mbed] Working path "C:\Users\Jenkins\workspace\mbed\platform-dragonfly-unit-tests\test" (library)
[mbed] Exec "python -u C:\Users\Jenkins\workspace\mbed\platform-dragonfly-unit-tests\test\mbed-os\tools\test.py -t GCC_ARM -m MTS_DRAGONFLY_F411RE -c --source C:\Users\Jenkins\workspace\mbed\platform-dragonfly-unit-tests\test --build C:\Users\Jenkins\workspace\mbed\platform-dragonfly-unit-tests\test\BUILD\tests\MTS_DRAGONFLY_F411RE\GCC_ARM --test-spec C:\Users\Jenkins\workspace\mbed\platform-dragonfly-unit-tests\test\BUILD\tests\MTS_DRAGONFLY_F411RE\GCC_ARM\test_spec.json -v" in C:\Users\Jenkins\workspace\mbed\platform-dragonfly-unit-tests\test
[mbed] Exec "mbedgt --test-spec C:\Users\Jenkins\workspace\mbed\platform-dragonfly-unit-tests\test\BUILD\tests\MTS_DRAGONFLY_F411RE\GCC_ARM\test_spec.json -V" in C:\Users\Jenkins\workspace\mbed\platform-dragonfly-unit-tests\test

C:\Users\Jenkins\workspace\mbed\platform-dragonfly-unit-tests\test>exit 0 
Finished: SUCCESS
`
