### ISSUE TITLE
WARNING: Cannot run icetea tests. Current folder does not contain TEST_APPS folder.

### ISSUE THREAD

**Issue by panuniverse** [ARMmbed/mbed-cli#770]
What's the reason?

**Comment by theotherjimmy** [comment]
You're using new mbed CLI, that supports an `--icetea` flag with an old version of Mbed OS. Perhaps that should be an error if you use `--icetea`

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-103*

**Comment by panuniverse** [comment]
![default](https://user-images.githubusercontent.com/22831610/47540012-a7ea1580-d905-11e8-9e35-f65500c4404f.JPG)

**Comment by panuniverse** [comment]
![Uploading 图片.png…]()

I have resolved that.
Because of the mbed_cli version, need to switch version.

**Comment by theotherjimmy** [comment]
@panuniverse The warning is a red herring: the reason it stopped is because the filesystem_recovery/resilience_functional test failed to compile.

**Comment by maclobdell** [comment]
I recently noticed this warning also.  I don't agree that it needs to indiscriminately warn users that they 'Cannot run icetea tests.' Especially, since most people will not be running Ice Tea tests.   They likely will not know what an Ice Tea test even is.  This warning might send them down a rabbit hole (e.g. this ticket).  Is it possible to suppress the warning?  To me, it is useless.  :)

**Comment by panuniverse** [comment]
@theotherjimmy Thank you,  you are right.

**Comment by panuniverse** [comment]
But the mbed_cli version is one reason which causes the Error.

**Comment by elm3** [comment]
Is this now fixed?  We closed the warning issue, and the original poster has upgrade CLI version to fix.

**Comment by naveenkaje** [comment]
With https://github.com/ARMmbed/mbed-cli/pull/776/commits, the WARNING does not show up. Issue can be closed.
