### ISSUE TITLE
Mbed import with `--depth` switch should affect mbed-os clone

### ISSUE THREAD

**Issue by theotherjimmy** [ARMmbed/mbed-cli#826]
from @fredlee12001 

> mbed import accepts an option to truncate the git history depth, `--depth`.
When I tried to import the PDMC project with `--depth 1`, I found that Mbed OS contained more than one commit in its history. See attached image
![image](https://user-images.githubusercontent.com/685409/51392781-b22e4100-1afb-11e9-953f-2df09f5b93a0.png)

**Comment by bridadan** [comment]
@theotherjimmy I believe this comes from the fact that you can't clone a specific commit with git. And since we pin specific commits with the `.lib` files, you usually don't get the commit you need if you only clone one of them.

That being said, I was wondering if it would work with _tags_: `git clone -b "mbed-os-5.10.2" --depth 1 https://github.com/armmbed/mbed-os`

That only gave me a history of one commit and quite a small `.git` folder (48.5 MB)

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-771*

**Comment by screamerbg** [comment]
This might be also related to locally cached copy of Mbed OS that has the full index tree. To save traffic, Mbed CLI will prefer to use the locally cached copy (200KB download vs 50MB)

**Comment by ciarmcom** [comment]
Thank you for raising this issue. Please note we have updated our policies and 
 now only defects should be raised directly in GitHub. Going forward questions and 
 enhancements will be considered in our forums, https://forums.mbed.com/ . If this 
 issue is still relevant please re-raise it there.
 This GitHub issue will now be closed.
