### ISSUE TITLE
Feature request: It would be nice to be able to comment configuration files, especially mbed_lib files

### ISSUE THREAD

**Issue by LiyouZhou** [ARMmbed/mbed-cli#849]
This will keep the documentation at the point of use, and deliver a much better ux.

The limitation of Json can be by-passed if we used some format that supports comments:
https://hjson.org/
https://yaml.org/
This new format support does not need to break json support. they can co-exist. mbed-cli will parse the file according to its file extension.

**Comment by ciarmcom** [comment]
*Internal Jira reference: https://jira.arm.com/browse/MBOCUSTRIA-871*

**Comment by loverdeg-ep** [comment]
Maybe this can become the start of a real specification for mbed_libs?

Either way I'd like dependency/package management to be handled by a more modular solution or entirely different tool.

**Comment by theotherjimmy** [comment]
@LiyouZhou This is an issue for mbed-os.

**Comment by LiyouZhou** [comment]
@LiyouZhou You have admin access to this repo, can you transfer this issue please? https://help.github.com/articles/transferring-an-issue-to-another-repository/

**Comment by mark-edgeworth** [comment]
As for the 'real spec for libraries'; this is a really important request but should be a new issue. We already have it captured internally as https://jira.arm.com/browse/IOTBTOOL-312. 
@LiyouZhou I, too, am irritated by the lack of comment in JSON, but this is unlikely to be fixed in the medium term as we'd have to convert all of our configs to YAML or something like it. I'm closing this original issue as won't fix.
